version: '3'
services:
  anaconda:
    container_name: anaconda
    build: 
      context: .
    volumes:
      - ./:/rapm-model/
    stdin_open: true
    tty: true

  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db